import type { AppSettings, LoadConfig, SamplingConfig } from '../src/types';

export const DEFAULT_LLAMA_SERVER_PORT = 8080;
export const LEGACY_LM_STUDIO_PORT = 1234;

export function migrateServerPort(port: number): number {
  return port === LEGACY_LM_STUDIO_PORT ? DEFAULT_LLAMA_SERVER_PORT : port;
}

export const defaultSampling: SamplingConfig = {
  temperature: 0.8,
  topK: 40,
  topP: 0.95,
  minP: 0.05,
  typicalP: 1,
  topNSigma: -1,
  xtcProbability: 0,
  xtcThreshold: 0.1,
  repeatLastN: 64,
  repeatPenalty: 1,
  presencePenalty: 0,
  frequencyPenalty: 0,
  dryMultiplier: 0,
  dryBase: 1.75,
  dryAllowedLength: 2,
  dryPenaltyLastN: -1,
  adaptiveTarget: -1,
  adaptiveDecay: 0.9,
  dynamicTemperatureRange: 0,
  dynamicTemperatureExponent: 1,
  mirostat: 0,
  mirostatTau: 5,
  mirostatEta: 0.1,
  seed: -1,
  maxTokens: 2048,
  reasoningEffort: 'auto',
  stop: [],
  ignoreEos: false,
  grammar: '',
  jsonSchema: '',
  samplerOrder: 'penalties;dry;top_n_sigma;top_k;typ_p;top_p;min_p;xtc;temperature',
};

export const defaultLoadConfig: LoadConfig = {
  onDemandLoading: true,
  maxLoadedModels: 1,
  contextSize: 8192,
  threads: -1,
  threadsBatch: -1,
  batchSize: 2048,
  ubatchSize: 512,
  gpuLayers: 'auto',
  device: '',
  splitMode: 'layer',
  tensorSplit: '',
  mainGpu: 0,
  fit: 'on',
  fitTarget: '',
  flashAttention: 'auto',
  kvOffload: true,
  opOffload: true,
  cacheTypeK: 'f16',
  cacheTypeV: 'f16',
  loadMode: 'mmap',
  numa: '',
  swaFull: false,
  noHost: false,
  repack: true,
  cpuMoe: false,
  cpuMoeLayers: 0,
  checkTensors: false,
  ropeScaling: '',
  ropeScale: 0,
  ropeFreqBase: 0,
  ropeFreqScale: 0,
  yarnOriginalContext: 0,
  yarnExtFactor: -1,
  yarnAttentionFactor: -1,
  yarnBetaSlow: -1,
  yarnBetaFast: -1,
  parallel: 1,
  continuousBatching: true,
  contextShift: false,
  cacheRam: 8192,
  cacheReuse: 0,
  promptCache: true,
  warmup: true,
  mmprojPath: '',
  mmprojOffload: true,
  imageMinTokens: 0,
  imageMaxTokens: 0,
  imageBatchTokens: 1024,
  lora: '',
  loraScaled: '',
  controlVector: '',
  controlVectorScaled: '',
  overrideKv: '',
  overrideTensor: '',
  reasoning: 'auto',
  reasoningFormat: 'auto',
  reasoningBudget: -1,
  reasoningPreserve: false,
  jinja: true,
  chatTemplate: '',
  chatTemplateFile: '',
  chatTemplateKwargs: '',
  embedding: false,
  reranking: false,
  pooling: '',
  embeddingNormalize: 2,
  speculativeType: 'none',
  draftModelPath: '',
  draftGpuLayers: 'auto',
  draftTokensMax: 3,
  draftTokensMin: 0,
  draftProbabilityMin: 0,
  ngramN: 12,
  ngramM: 48,
  ngramMinHits: 1,
  host: '127.0.0.1',
  port: DEFAULT_LLAMA_SERVER_PORT,
  alias: '',
  apiKey: '',
  corsOrigins: 'localhost',
  metrics: true,
  props: true,
  slots: true,
  slotSavePath: '',
  mediaPath: '',
  sleepIdleSeconds: 0,
  timeout: 3600,
  httpThreads: -1,
  tools: [],
  agent: false,
  extraArgs: '',
};

export const DEFAULT_APP_SETTINGS: AppSettings = {
  runtimePath: '',
  modelDirectories: [],
  downloadDirectory: '',
  huggingFaceToken: '',
  startServerOnLaunch: true,
  minimizeToTray: false,
  theme: 'dark',
  defaultLoadConfig: { ...defaultLoadConfig },
  defaultSampling: { ...defaultSampling },
  presets: [
    {
      id: 'balanced',
      name: 'Balanced',
      systemPrompt: '',
      sampling: { ...defaultSampling },
    },
    {
      id: 'precise',
      name: 'Precise',
      systemPrompt: 'Be accurate, concise, and explicit about uncertainty.',
      sampling: {
        ...defaultSampling,
        temperature: 0.3,
        topP: 0.9,
        minP: 0.02,
      },
    },
    {
      id: 'creative',
      name: 'Creative',
      systemPrompt: 'Explore original ideas and vivid alternatives.',
      sampling: {
        ...defaultSampling,
        temperature: 1,
        topP: 0.98,
        minP: 0.03,
      },
    },
  ],
  offlineMode: false,
  autoPortFallback: true,
};

export function makeDefaultSettings(defaultModelDirectory: string): AppSettings {
  return {
    ...DEFAULT_APP_SETTINGS,
    modelDirectories: [defaultModelDirectory],
    downloadDirectory: defaultModelDirectory,
  };
}
