/**
 * Rasterizes build/icon.svg into the app icons used by Electron and electron-builder.
 *
 * Run with:  npm run icon      (executes this file with the electron binary)
 *
 * Outputs:
 *   build/icon.ico        multi-size Windows icon (taskbar, shortcuts, installer)
 *   build/icon.png        512px icon for electron-builder / non-Windows targets
 *   public/icon.{ico,png} copies Vite emits into dist/ for the runtime window
 *   public/logo-mark.svg  plate-free llama, for the titlebar and nav rail
 */
import { app, BrowserWindow, nativeImage } from 'electron'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const sourceSize = 1024
const icoSizes = [16, 24, 32, 48, 64, 128, 256]

/**
 * Renders build/icon.svg offscreen at high resolution. Returns the rasterized
 * icon plus the bounding box of the #mark group, measured by the same engine
 * that drew it.
 */
async function renderSource() {
  const svg = readFileSync(path.join(rootDirectory, 'build/icon.svg'), 'utf8')
  // The SVG carries a viewBox, so stretching it to the viewport scales it cleanly.
  const page = `<!doctype html><meta charset="utf-8">
    <style>html,body{margin:0;background:transparent}
    svg{display:block;width:100vw;height:100vh}</style>${svg}`

  const window = new BrowserWindow({
    width: sourceSize,
    height: sourceSize,
    show: false,
    frame: false,
    transparent: true,
    backgroundColor: '#00000000',
    webPreferences: { offscreen: true, backgroundThrottling: false },
  })
  await window.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(page)}`)
  const image = await window.webContents.capturePage()
  const markBounds = await window.webContents.executeJavaScript(
    `(() => { const b = document.getElementById('mark').getBBox();
      return { x: b.x, y: b.y, width: b.width, height: b.height } })()`,
  )
  window.destroy()
  return { image, markBounds, svg }
}

/**
 * Derives the in-app logo: the #mark group on a transparent background, cropped
 * to its own bounds so it fills whatever box the UI gives it. Kept as SVG so the
 * 16px titlebar copy stays sharp on any display scale.
 */
function buildLogoMark(svg, bounds) {
  const defs = svg.match(/<defs>[\s\S]*?<\/defs>/)?.[0]
  const mark = svg.match(/<g id="mark">[\s\S]*<\/g>/)?.[0]
  if (!defs || !mark) throw new Error('build/icon.svg is missing <defs> or the #mark group')

  // Stroked edges sit slightly outside the geometric bbox, so pad the crop.
  const pad = 8
  const round = (value) => Math.round(value * 100) / 100
  const viewBox = [
    round(bounds.x - pad),
    round(bounds.y - pad),
    round(bounds.width + pad * 2),
    round(bounds.height + pad * 2),
  ].join(' ')

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">
  <!-- Generated by scripts/make-icon.mjs from build/icon.svg - do not edit. -->
${defs}
${mark}
</svg>
`
}

/**
 * Packs images as an .ico. Entries use the uncompressed DIB format (32bpp BGRA,
 * bottom-up, with a trailing AND mask) which every Windows shell version reads.
 */
function buildIco(entries) {
  const directory = Buffer.alloc(6 + entries.length * 16)
  directory.writeUInt16LE(0, 0) // reserved
  directory.writeUInt16LE(1, 2) // type: icon
  directory.writeUInt16LE(entries.length, 4)

  const payloads = []
  let offset = directory.length

  entries.forEach(({ size, bgra }, index) => {
    const maskStride = ((size + 31) >> 5) * 4 // AND mask rows are 4-byte aligned
    const header = Buffer.alloc(40)
    header.writeUInt32LE(40, 0) // BITMAPINFOHEADER size
    header.writeInt32LE(size, 4)
    header.writeInt32LE(size * 2, 8) // height counts colour + mask planes
    header.writeUInt16LE(1, 12) // planes
    header.writeUInt16LE(32, 14) // bits per pixel
    header.writeUInt32LE(size * size * 4 + maskStride * size, 20) // image byte count

    // DIB rows run bottom-up, so flip the rasterized rows.
    const pixels = Buffer.alloc(size * size * 4)
    for (let row = 0; row < size; row += 1) {
      bgra.copy(pixels, row * size * 4, (size - 1 - row) * size * 4, (size - row) * size * 4)
    }
    const mask = Buffer.alloc(maskStride * size) // fully opaque; alpha lives in the DIB
    const payload = Buffer.concat([header, pixels, mask])
    payloads.push(payload)

    const entry = 6 + index * 16
    directory.writeUInt8(size >= 256 ? 0 : size, entry) // 0 means 256
    directory.writeUInt8(size >= 256 ? 0 : size, entry + 1)
    directory.writeUInt8(0, entry + 2) // palette colours
    directory.writeUInt8(0, entry + 3) // reserved
    directory.writeUInt16LE(1, entry + 4) // colour planes
    directory.writeUInt16LE(32, entry + 6) // bits per pixel
    directory.writeUInt32LE(payload.length, entry + 8)
    directory.writeUInt32LE(offset, entry + 12)
    offset += payload.length
  })

  return Buffer.concat([directory, ...payloads])
}

async function main() {
  await app.whenReady()
  const { image: source, markBounds, svg } = await renderSource()

  const entries = icoSizes.map((size) => {
    const resized = source.resize({ width: size, height: size, quality: 'best' })
    return { size, bgra: resized.toBitmap() }
  })

  mkdirSync(path.join(rootDirectory, 'public'), { recursive: true })
  const ico = buildIco(entries)
  const png512 = source.resize({ width: 512, height: 512, quality: 'best' }).toPNG()

  // build/ feeds electron-builder; public/ is copied into dist/ by Vite and is
  // what the packaged main process loads at runtime.
  writeFileSync(path.join(rootDirectory, 'build/icon.ico'), ico)
  writeFileSync(path.join(rootDirectory, 'build/icon.png'), png512)
  writeFileSync(path.join(rootDirectory, 'public/icon.ico'), ico)
  writeFileSync(path.join(rootDirectory, 'public/icon.png'), png512)
  writeFileSync(path.join(rootDirectory, 'public/logo-mark.svg'), buildLogoMark(svg, markBounds))

  console.log(`icons written (${icoSizes.join(', ')}): build/icon.{ico,png}, public/icon.{ico,png}`)
  console.log('logo written: public/logo-mark.svg')
  app.quit()
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
